server:
  port: 4042
  servlet:
    context-path: /employee
spring:
  datasource:
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    url: ${DB_URLjdbc:mysql://mysqldb:3306/emp}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
